install:
	sudo cp -v registry-ls registry-rmtag registry-lslayers registry-cleaner ../bin/docker-ls ../bin/docker-rm /usr/local/bin/
	sudo chmod 755 /usr/local/bin/registry-ls
	sudo chmod 755 /usr/local/bin/registry-lslayers
	sudo chmod 755 /usr/local/bin/registry-rmtag
	sudo chmod 755 /usr/local/bin/registry-cleaner
	sudo chmod 755 /usr/local/bin/docker-ls
	sudo chmod 755 /usr/local/bin/docker-rm

